### ISSUE TITLE
Exam Notifier Menu from Options menu

### ISSUE THREAD

**Issue by paullyb17** [AnKing-VIP/exam-notifier#17]
#### Problem description

I am unable to access the menu to set up the exam notifier. I go to the deck option menu and scroll down to add ons and there is hyperlink next to Looking for exam notifier's options? Click Here! When I click on the click here, the error messager i included below pops up and nothing happens.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ X] I've restarted Anki to see if it helps
 - [X ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X ] I've tried to disable other add-ons to see if there are any interactions present
 - [X ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
I'm on anki 2.1.64 but do not have this option.
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.64 (581f82c5) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-10-05 22:48:12
Add-ons possibly involved: ⁨Exam Notifier⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 656, in _onBridgeCmd
  File "_aqt.hooks", line 5183, in __call__
  File "/Users/paulbowman/Library/Application Support/Anki2/addons21/exam_notifier/deck_options.py", line 150, in on_webview_did_receive_js_message
    DeckConf(self._main_window, deck_legacy)
  File "aqt.deckconf", line 40, in __init__
  File "_aqt.hooks", line 1829, in __call__
  File "/Users/paulbowman/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 109, in on_deck_config_gui_loaded
    deck_config_tab = self._factory(parent=deck_conf_dialog)
  File "/Users/paulbowman/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 63, in __init__
    self._qdatetime_from_epoch(unix_time_now)
  File "/Users/paulbowman/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 89, in _qdatetime_from_epoch
    qdatetime.setTime_t(unix_epoch)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

```

**Comment by AnKingMed** [comment]
This should hopefully be working now on later versions. I have it working on 23.10. Is it still giving you this error?
